name: Publish
on:
  push:
    branches: ['v*']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies    
        run: pip install mkdocs-material mike
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - name: Release docs website and API reference
        run: |
          git config --global user.name Docs Deploy
          git config --global user.email docs@deploy.com
          cd tomodo-documentation
          mike deploy --push --update-aliases "${{  github.ref_name }}" latest
          mike set-default --push latest
